name: djwaitaminute_ssr
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.3
  jaspr_router: ^0.8.1
  lints: ^6.1.0

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.13
  jaspr_builder: ^0.22.3

jaspr:
  mode: server
